#!/bin/sh
# Weft ID install script
#
# Downloads production files, generates secrets, and writes .env.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/pageloom/weft-id/main/install.sh | bash
#   # or
#   ./install.sh
#
# Prerequisites: curl, openssl, POSIX shell
# Works on Linux and macOS.

set -e

REPO="pageloom/weft-id"
RAW_URL="https://raw.githubusercontent.com/${REPO}"
API_URL="https://api.github.com/repos/${REPO}"
FILES="Caddyfile weftid"

# --- Helpers ---------------------------------------------------------------

die() { printf "Error: %s\n" "$1" >&2; exit 1; }

prompt() {
    # Read from /dev/tty so the script works when piped via curl | bash
    printf "%s" "$1" >/dev/tty
    read -r REPLY </dev/tty
}

check_prereqs() {
    for cmd in curl openssl; do
        command -v "$cmd" >/dev/null 2>&1 || die "$cmd is required but not installed."
    done
}

# --- Resolve release -------------------------------------------------------

get_ref() {
    # Try the latest GitHub release tag. Fall back to main if none exists.
    tag=$(curl -fsSL "${API_URL}/releases/latest" 2>/dev/null \
        | grep '"tag_name"' | head -1 | sed 's/.*: *"//;s/".*//') || true
    if [ -n "$tag" ]; then
        echo "$tag"
    else
        echo "main"
    fi
}

version_from_ref() {
    # Strip leading "v" from a tag (v1.2.3 -> 1.2.3). Passthrough otherwise.
    ref="$1"
    case "$ref" in
        v*) echo "${ref#v}" ;;
        main) echo "latest" ;;
        *) echo "$ref" ;;
    esac
}

# --- Download files ---------------------------------------------------------

download_files() {
    ref="$1"
    echo "Downloading from ${REPO}@${ref} ..."

    # Rename production compose file so 'docker compose' finds it by default
    curl -fsSL "${RAW_URL}/${ref}/docker-compose.production.yml" -o "docker-compose.yml" \
        || die "Failed to download docker-compose.production.yml"
    echo "  docker-compose.yml"

    for f in $FILES; do
        curl -fsSL "${RAW_URL}/${ref}/${f}" -o "$f" || die "Failed to download ${f}"
        echo "  $f"
    done

    chmod +x weftid
}

# --- Interactive prompts ----------------------------------------------------

prompt_domain() {
    echo "" >/dev/tty
    echo "Domain (required)" >/dev/tty
    echo "  Tenants are accessed via subdomains (e.g., acme.id.example.com)." >/dev/tty
    echo "  DNS must point both the apex and *.apex to this server." >/dev/tty
    echo "" >/dev/tty
    while [ -z "$BASE_DOMAIN" ]; do
        prompt "BASE_DOMAIN: "
        BASE_DOMAIN="$REPLY"
        [ -z "$BASE_DOMAIN" ] && echo "  Domain is required." >/dev/tty
    done
}

prompt_smtp() {
    echo "" >/dev/tty
    echo "Email / SMTP (press Enter to skip, configure later in .env)" >/dev/tty
    echo "" >/dev/tty

    prompt "SMTP_HOST: "
    SMTP_HOST="$REPLY"

    if [ -n "$SMTP_HOST" ]; then
        prompt "SMTP_PORT [587]: "
        SMTP_PORT="${REPLY:-587}"

        prompt "SMTP_USER: "
        SMTP_USER="$REPLY"

        prompt "SMTP_PASS: "
        SMTP_PASS="$REPLY"

        prompt "FROM_EMAIL [no-reply@${BASE_DOMAIN}]: "
        FROM_EMAIL="${REPLY:-no-reply@${BASE_DOMAIN}}"
    else
        SMTP_PORT="587"
        SMTP_USER=""
        SMTP_PASS=""
        FROM_EMAIL=""
    fi
}

# --- Write .env -------------------------------------------------------------

write_env() {
    version="$1"

    cat > .env <<ENVEOF
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

# Version
WEFT_VERSION=${version}

# Domain
BASE_DOMAIN=${BASE_DOMAIN}

# Secrets (auto-generated)
SECRET_KEY=${SECRET_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Email / SMTP
EMAIL_BACKEND=smtp
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_TLS=true
FROM_EMAIL=${FROM_EMAIL}

# Optional
ENABLE_OPENAPI_DOCS=false
ENVEOF

    echo ""
    echo "  .env written"
}

# --- Main -------------------------------------------------------------------

main() {
    echo ""
    echo "Weft ID Install"
    echo "==============="

    check_prereqs

    # Guard against overwriting an existing .env
    if [ -f .env ]; then
        prompt "An existing .env file was found. Overwrite? [y/N] "
        case "$REPLY" in
            [yY]*) ;;
            *) echo "Aborted." >/dev/tty; exit 0 ;;
        esac
    fi

    # Resolve version and download
    ref=$(get_ref)
    version=$(version_from_ref "$ref")
    download_files "$ref"

    # Generate secrets
    SECRET_KEY=$(openssl rand -base64 32)
    POSTGRES_PASSWORD=$(openssl rand -base64 32)

    # Interactive configuration
    prompt_domain
    prompt_smtp
    write_env "$version"

    echo ""
    echo "Next steps:"
    echo "  1. Review .env and adjust settings if needed"
    echo "  2. Start Weft ID:"
    echo ""
    echo "     ./weftid up"
    echo ""
    echo "  Run ./weftid help to see all available commands."
    echo ""
}

main
