[pytest]
testpaths = tests
pythonpath = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --strict-markers
    --tb=short
    -n auto
    --ignore=tests/e2e
filterwarnings =
    ignore::DeprecationWarning:onelogin.*:
    ignore:The `name` is not the first parameter anymore:DeprecationWarning:starlette.templating:
