#!/usr/bin/env bash
# Bootstrap the OpenID Foundation conformance suite for testing WeftID's
# OpenID Provider.
#
# The suite runtime (compose.yml, the Mongo data directory, and the
# downloaded runner scripts) lives entirely OUTSIDE this repo by default,
# under `~/.local/share/weft-id/oidc-conformance/`. Override with
# `OIDC_CONFORMANCE_DIR` or `--dir <path>`. Nothing in this script writes
# inside the weft-id checkout.
#
# The suite joins WeftID's dev compose network (`devnet`) as an external
# network so that its headless browser can reach the conformance tenant
# through the dev reverse proxy, and so WeftID's containers can reach the
# suite's callback URLs. The dev stack must therefore be running first
# (`make up`).
#
# The conformance suite is a separate open-source project (Apache 2.0)
# maintained by the OpenID Foundation; see
# https://gitlab.com/openid/conformance-suite. WeftID does not bundle,
# vendor, or redistribute any of its code or images. This script pulls
# the public images for a pinned release at runtime and the runner
# (`dev/oidc_conformance.py`) downloads the suite's `run-test-plan.py`
# from the same release tag.
#
# Usage:
#   dev/oidc-conformance.sh up [--dir <path>] [--tag <release>]
#   dev/oidc-conformance.sh down
#   dev/oidc-conformance.sh destroy
#   dev/oidc-conformance.sh status
#   dev/oidc-conformance.sh logs [<service>]
#   dev/oidc-conformance.sh info
#   dev/oidc-conformance.sh help
#
# Running the plans is `make oidc-conformance` (see dev/oidc-conformance.md).

set -euo pipefail

DEFAULT_DIR="${HOME}/.local/share/weft-id/oidc-conformance"
# Pinned suite release. Bump deliberately: a new release can add tests, and
# the results page records the version a run was made against.
DEFAULT_TAG="release-v5.2.4"
# The suite's canonical public hostname; it resolves to 127.0.0.1 in public
# DNS (for the host) and is aliased on the Docker networks (for containers).
SUITE_HOST="localhost.emobix.co.uk"
SUITE_PORT="8443"
# Container name of WeftID's dev app; used to discover the devnet network
# name, which depends on the compose project name (the checkout directory).
WEFTID_APP_CONTAINER="dev_app"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

CMD="${1:-help}"
shift || true

DIR="${OIDC_CONFORMANCE_DIR:-${DEFAULT_DIR}}"
TAG="${OIDC_CONFORMANCE_TAG:-${DEFAULT_TAG}}"
LOGS_SERVICE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dir)
            DIR="$2"
            shift 2
            ;;
        --tag)
            TAG="$2"
            shift 2
            ;;
        -h|--help)
            CMD="help"
            shift
            ;;
        *)
            if [[ "${CMD}" == "logs" && -z "${LOGS_SERVICE}" ]]; then
                LOGS_SERVICE="$1"
                shift
            else
                echo "error: unexpected argument: $1" >&2
                exit 2
            fi
            ;;
    esac
done

COMPOSE_FILE="${DIR}/compose.yml"
ENV_FILE="${DIR}/.env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

die() { echo "error: $*" >&2; exit 1; }

require_docker() {
    command -v docker >/dev/null 2>&1 || die "docker is not on PATH"
    docker compose version >/dev/null 2>&1 || die "'docker compose' subcommand not available"
}

compose() {
    docker compose --project-directory "${DIR}" -f "${COMPOSE_FILE}" "$@"
}

# The dev compose project names its network "<project>_devnet". Read it off
# the running app container rather than guessing the project name.
weftid_devnet() {
    local net
    net="$(docker inspect "${WEFTID_APP_CONTAINER}" \
        --format '{{range $k, $_ := .NetworkSettings.Networks}}{{$k}}{{end}}' 2>/dev/null || true)"
    [[ -n "${net}" ]] || die "WeftID dev stack is not running (container ${WEFTID_APP_CONTAINER} not found). Run 'make up' first."
    echo "${net}"
}

write_compose() {
    cat >"${COMPOSE_FILE}" <<'COMPOSE_YAML'
# Auto-generated by dev/oidc-conformance.sh. Re-runs of `up` leave an
# existing file alone; delete it to regenerate. Yours to tweak locally.
#
# Adapted from the conformance suite's docker-compose-prebuilt.yml:
#   https://gitlab.com/openid/conformance-suite/-/blob/master/docker-compose-prebuilt.yml
# (Apache 2.0, OpenID Foundation). Differences: pinned image tags, fixed
# container names, and the `devnet` external network shared with WeftID's
# dev stack.

services:
  mongodb:
    image: ${MONGODB_IMAGE:-mongo:6.0.13}
    container_name: weft_oidc_conformance_mongo
    volumes:
      - ./mongo/data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  nginx:
    image: registry.gitlab.com/openid/conformance-suite/nginx:${SUITE_TAG}
    container_name: weft_oidc_conformance_nginx
    ports:
      - "${SUITE_PORT}:8443"
    networks:
      default:
        aliases:
          # The suite's own outbound requests to its public hostname must
          # reach this nginx (in-container DNS otherwise resolves the public
          # name to 127.0.0.1).
          - ${SUITE_HOST}
      devnet:
        aliases:
          # Same for WeftID's containers on devnet (redirect_uri callbacks,
          # and later back-channel logout / jwks_uri fetches).
          - ${SUITE_HOST}
    depends_on:
      - server
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  server:
    image: registry.gitlab.com/openid/conformance-suite:${SUITE_TAG}
    container_name: weft_oidc_conformance_server
    environment:
      BASE_URL: https://${SUITE_HOST}:${SUITE_PORT}
      BASE_MTLS_URL: https://${SUITE_HOST}:8444
      MONGODB_HOST: mongodb
      # `dev` disables the suite's login and API tokens (local use only).
      SPRING_PROFILES_ACTIVE: dev
      OIDC_GOOGLE_CLIENTID: google-client
      OIDC_GOOGLE_SECRET: google-secret
      OIDC_GITLAB_CLIENTID: gitlab-client
      OIDC_GITLAB_SECRET: gitlab-secret
    networks:
      - default
      # The headless browser and discovery/JWKS fetches reach the
      # conformance tenant via the dev reverse proxy's devnet alias
      # (see dev/docker-compose.yml).
      - devnet
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

networks:
  devnet:
    external: true
    name: ${WEFTID_DEVNET}
COMPOSE_YAML
}

write_env() {
    local devnet
    devnet="$(weftid_devnet)"
    cat >"${ENV_FILE}" <<ENV_FILE
# Auto-generated by dev/oidc-conformance.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Regenerated on every 'up' (the devnet name depends on where WeftID is
# checked out). No secrets live here.

SUITE_TAG=${TAG}
SUITE_HOST=${SUITE_HOST}
SUITE_PORT=${SUITE_PORT}
WEFTID_DEVNET=${devnet}
ENV_FILE
}

print_info() {
    cat <<INFO

  OIDC conformance suite (OpenID Foundation)
  ------------------------------------------
  Project dir : ${DIR}
  Suite UI    : https://${SUITE_HOST}:${SUITE_PORT}/
  Release     : ${TAG}
  WeftID host : https://oidc-conformance.weftid.localhost (tenant is
                provisioned by the runner on first 'make oidc-conformance')

  The suite's nginx uses a self-signed certificate: accept the browser
  warning when opening the UI. Test results are browsable there under
  "Test plans" after a run.

  Run the plans:
    make oidc-conformance                    # Basic, Config, Form Post OP
    make oidc-conformance ARGS="--verbose"   # print expected-failure templates
    make oidc-conformance ARGS="--list"      # show plans without running

  Prerequisites for a run:
    - WeftID dev stack up (make up) with BYPASS_OTP=true in .env so the
      scripted browser can pass the MFA step with any 6-digit code
    - the reverse proxy recreated since dev/docker-compose.yml gained the
      oidc-conformance.weftid.localhost alias (make up does this)

  Lifecycle:
    make oidc-conformance-down      # stop containers (keep Mongo data)
    make oidc-conformance-destroy   # stop + wipe Mongo data + remove dir
    make oidc-conformance-logs      # follow combined logs
    make oidc-conformance-status    # docker compose ps

  Walkthrough: dev/oidc-conformance.md

INFO
}

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

cmd_up() {
    require_docker
    mkdir -p "${DIR}/mongo/data"
    [[ -f "${COMPOSE_FILE}" ]] || write_compose
    write_env
    compose up -d
    print_info
}

cmd_down() {
    require_docker
    [[ -f "${COMPOSE_FILE}" ]] || die "no suite at ${DIR} (run 'up' first)"
    compose down
}

cmd_destroy() {
    require_docker
    if [[ -f "${COMPOSE_FILE}" ]]; then
        compose down -v
    fi
    # Be precise: only remove the suite directory itself, never a parent.
    # Refuses to remove anything whose path does not contain
    # "oidc-conformance" (defense in depth).
    if [[ -d "${DIR}" && "${DIR}" == *"oidc-conformance"* ]]; then
        rm -rf "${DIR}"
        echo "removed ${DIR}"
    else
        die "refusing to remove ${DIR} (path does not contain 'oidc-conformance')"
    fi
}

cmd_status() {
    require_docker
    [[ -f "${COMPOSE_FILE}" ]] || die "no suite at ${DIR} (run 'up' first)"
    compose ps
}

cmd_logs() {
    require_docker
    [[ -f "${COMPOSE_FILE}" ]] || die "no suite at ${DIR} (run 'up' first)"
    if [[ -n "${LOGS_SERVICE}" ]]; then
        compose logs -f "${LOGS_SERVICE}"
    else
        compose logs -f
    fi
}

cmd_info() {
    print_info
}

cmd_help() {
    sed -n '1,/^set -euo pipefail$/p' "$0" | sed -n '/^#/p' | sed 's/^# \{0,1\}//'
}

case "${CMD}" in
    up)      cmd_up      ;;
    down)    cmd_down    ;;
    destroy) cmd_destroy ;;
    status)  cmd_status  ;;
    logs)    cmd_logs    ;;
    info)    cmd_info    ;;
    help|"") cmd_help    ;;
    *)       die "unknown command: ${CMD} (run 'help' for usage)" ;;
esac
