#!/usr/bin/env bash
# Bootstrap a local Authentik instance for testing WeftID outbound SCIM.
#
# The Authentik runtime (compose.yml, .env with generated secrets, the
# `data/` / `certs/` / `custom-templates/` mounts, and the postgres
# volume) lives entirely OUTSIDE this repo by default -- under
# `~/.local/share/weft-id/scim-testbed/authentik/`. Override with
# `SCIM_TESTBED_DIR` or `--dir <path>`. Nothing in this script writes
# inside the weft-id checkout.
#
# Authentik is a separate open-source project (MIT) maintained by
# Authentik Security Inc.; see https://goauthentik.io. The compose
# template this script writes is adapted from their official docs
# (CC BY-SA 4.0). WeftID does not bundle, vendor, or redistribute
# any Authentik code or images -- the script just pulls the public
# image at runtime.
#
# Usage:
#   dev/scim-testbed.sh up [--dir <path>] [--port <http>] [--tag <ver>]
#   dev/scim-testbed.sh down
#   dev/scim-testbed.sh destroy
#   dev/scim-testbed.sh status
#   dev/scim-testbed.sh logs [<service>]
#   dev/scim-testbed.sh info
#   dev/scim-testbed.sh help
#
# See dev/scim-testbed.md for the full walkthrough (creating the SCIM
# source in Authentik, copying the bearer token into WeftID, verifying
# pushes).

set -euo pipefail

DEFAULT_DIR="${HOME}/.local/share/weft-id/scim-testbed/authentik"
DEFAULT_PORT_HTTP="9000"
DEFAULT_PORT_HTTPS="9443"
DEFAULT_TAG="2026.5.0"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

CMD="${1:-help}"
shift || true

DIR="${SCIM_TESTBED_DIR:-${DEFAULT_DIR}}"
PORT_HTTP="${SCIM_TESTBED_PORT_HTTP:-${DEFAULT_PORT_HTTP}}"
PORT_HTTPS="${SCIM_TESTBED_PORT_HTTPS:-${DEFAULT_PORT_HTTPS}}"
TAG="${SCIM_TESTBED_TAG:-${DEFAULT_TAG}}"
LOGS_SERVICE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dir)
            DIR="$2"
            shift 2
            ;;
        --port)
            PORT_HTTP="$2"
            shift 2
            ;;
        --tag)
            TAG="$2"
            shift 2
            ;;
        -h|--help)
            CMD="help"
            shift
            ;;
        *)
            # First non-flag arg after `logs` is the service name; other
            # commands have no positional args.
            if [[ "${CMD}" == "logs" && -z "${LOGS_SERVICE}" ]]; then
                LOGS_SERVICE="$1"
                shift
            else
                echo "error: unexpected argument: $1" >&2
                exit 2
            fi
            ;;
    esac
done

COMPOSE_FILE="${DIR}/compose.yml"
ENV_FILE="${DIR}/.env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

die() { echo "error: $*" >&2; exit 1; }

require_docker() {
    command -v docker >/dev/null 2>&1 || die "docker is not on PATH"
    docker compose version >/dev/null 2>&1 || die "'docker compose' subcommand not available"
}

compose() {
    docker compose --project-directory "${DIR}" -f "${COMPOSE_FILE}" "$@"
}

generate_secret() {
    # openssl is in any base macOS / Linux dev environment; fall back to
    # /dev/urandom + xxd if it's missing.
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$1"
    else
        head -c "$1" /dev/urandom | xxd -p -c 999
    fi
}

write_compose() {
    cat >"${COMPOSE_FILE}" <<'COMPOSE_YAML'
# Auto-generated by dev/scim-testbed.sh. Re-runs of `up` leave an
# existing file alone; delete it to regenerate. Yours to tweak
# locally.
#
# Adapted from Authentik's official docker-compose example, which is
# part of the Authentik documentation (CC BY-SA 4.0):
#   https://docs.goauthentik.io/docs/install-config/install/docker-compose
#   https://github.com/goauthentik/authentik/blob/main/LICENSE
#
# Authentik (c) Jens Langhammer and Authentik Security Inc.

services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: weft_scim_testbed_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG}
    container_name: weft_scim_testbed_server
    restart: unless-stopped
    command: server
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    volumes:
      - ./data:/data
      - ./custom-templates:/templates
    shm_size: 512mb
    depends_on:
      postgresql:
        condition: service_healthy

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG}
    container_name: weft_scim_testbed_worker
    restart: unless-stopped
    command: worker
    user: root
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./certs:/certs
      - ./custom-templates:/templates
    shm_size: 512mb
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  database:
    driver: local
COMPOSE_YAML
}

write_env() {
    local pg_pass authentik_secret
    pg_pass="$(generate_secret 32)"
    authentik_secret="$(generate_secret 64)"
    cat >"${ENV_FILE}" <<ENV_FILE
# Auto-generated by dev/scim-testbed.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Secrets are random per-host -- never commit this file anywhere.

PG_PASS=${pg_pass}
AUTHENTIK_SECRET_KEY=${authentik_secret}
AUTHENTIK_ERROR_REPORTING__ENABLED=false
COMPOSE_PORT_HTTP=${PORT_HTTP}
COMPOSE_PORT_HTTPS=${PORT_HTTPS}
AUTHENTIK_TAG=${TAG}
ENV_FILE
    chmod 600 "${ENV_FILE}"
}

print_info() {
    local target_url="http://localhost:${PORT_HTTP}"
    local docker_target="http://host.docker.internal:${PORT_HTTP}/source/scim/weftid/v2/"
    cat <<INFO

  SCIM testbed (Authentik)
  ------------------------
  Project dir : ${DIR}
  Web UI      : ${target_url}
  Admin setup : ${target_url}/if/flow/initial-setup/
  Tag         : ${TAG}

  First-run flow:
    1. Open the "Admin setup" URL in a browser and create the akadmin password.
    2. In the Authentik Admin UI: Directory -> Federation -> Sources.
       Create a SCIM Source (name: WeftID, slug: weftid). Save.
    3. Open the new source. Copy the bearer token (eye icon) and note the
       SCIM Base URL.
    4. In WeftID's SCIM tab on any SP:
       - Application type: Generic SCIM 2.0
       - Target URL     : ${docker_target}
         (host.docker.internal is allowed in IS_DEV mode; production
          deployments would use the SP's real URL.)
       - Click "Import existing token" and paste Authentik's token.
    5. Grant a group access on the SP. The membership change enqueues
       SCIM pushes that should land in Authentik's Directory -> Users.

  Lifecycle:
    dev/scim-testbed.sh down      # stop containers (keep DB volume)
    dev/scim-testbed.sh destroy   # stop + wipe DB volume + remove dir
    dev/scim-testbed.sh logs      # follow combined logs
    dev/scim-testbed.sh status    # docker compose ps

INFO
}

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

cmd_up() {
    require_docker
    mkdir -p "${DIR}/data" "${DIR}/certs" "${DIR}/custom-templates"
    [[ -f "${COMPOSE_FILE}" ]] || write_compose
    [[ -f "${ENV_FILE}" ]] || write_env
    compose up -d
    print_info
}

cmd_down() {
    require_docker
    [[ -f "${COMPOSE_FILE}" ]] || die "no testbed at ${DIR} (run 'up' first)"
    compose down
}

cmd_destroy() {
    require_docker
    if [[ -f "${COMPOSE_FILE}" ]]; then
        compose down -v
    fi
    # Be precise: only remove the testbed directory itself, never a
    # parent. Guarded by the compose-file existence check above and by
    # the leading path component (refuses to remove anything that does
    # not contain "scim-testbed" in its path -- defense in depth).
    if [[ -d "${DIR}" && "${DIR}" == *"scim-testbed"* ]]; then
        rm -rf "${DIR}"
        echo "removed ${DIR}"
    else
        die "refusing to remove ${DIR} (path does not contain 'scim-testbed')"
    fi
}

cmd_status() {
    require_docker
    [[ -f "${COMPOSE_FILE}" ]] || die "no testbed at ${DIR} (run 'up' first)"
    compose ps
}

cmd_logs() {
    require_docker
    [[ -f "${COMPOSE_FILE}" ]] || die "no testbed at ${DIR} (run 'up' first)"
    if [[ -n "${LOGS_SERVICE}" ]]; then
        compose logs -f "${LOGS_SERVICE}"
    else
        compose logs -f
    fi
}

cmd_info() {
    print_info
}

cmd_help() {
    sed -n '1,/^set -euo pipefail$/p' "$0" | sed -n '/^#/p' | sed 's/^# \{0,1\}//'
}

case "${CMD}" in
    up)      cmd_up      ;;
    down)    cmd_down    ;;
    destroy) cmd_destroy ;;
    status)  cmd_status  ;;
    logs)    cmd_logs    ;;
    info)    cmd_info    ;;
    help|"") cmd_help    ;;
    *)       die "unknown command: ${CMD} (run 'help' for usage)" ;;
esac
